from pathlib import Path
import sys

class GeneratedFile(object):
    def __init__(self, header_source: str, output_file: str):
        self.lines = [
            f"// Autogenerated by {Path(sys.argv[0]).resolve()}! Do not Edit!",
            f"#include <{header_source}>",
        ]
        self.outfile = output_file

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        with open(self.outfile, "w") as f:
            f.write("\n".join(self.lines))

    def add_include(self, include: str):
        self.lines.append(f"#include <{include}>")

    def append_lines(self, lines: list[str]):
        self.lines.extend(lines)
