from __future__ import annotations

import io
import sys
import zipfile
from pathlib import Path


def parse_property(data: bytes, wanted_property: str) -> list[tuple[int, int]]:
    ranges = []

    with zipfile.ZipFile(io.BytesIO(data)) as zf:
        with zf.open("DerivedCoreProperties.txt") as f:
            for raw_line in io.TextIOWrapper(f, encoding="utf-8"):
                line = raw_line.split("#", 1)[0].strip()

                if not line:
                    continue

                codepoints, property_name = map(
                    str.strip,
                    line.split(";", 1),
                )

                if property_name != wanted_property:
                    continue

                if ".." in codepoints:
                    first, last = codepoints.split("..")
                    start = int(first, 16)
                    end = int(last, 16)
                else:
                    start = end = int(codepoints, 16)

                ranges.append((start, end))

    return ranges


def merge_ranges(ranges: list[tuple[int, int]]) -> list[tuple[int, int]]:
    if not ranges:
        return []

    ranges = sorted(ranges)

    merged = [ranges[0]]

    for start, end in ranges[1:]:
        prev_start, prev_end = merged[-1]

        if start <= prev_end + 1:
            merged[-1] = (prev_start, max(prev_end, end))
        else:
            merged.append((start, end))

    return merged


def cpp_ranges(name: str, ranges: list[tuple[int, int]]) -> str:
    lines = [
        f"static table<empty_struct>::elem {name}_ranges[] = {{",
    ]

    for start, end in ranges:
        lines.append(
            f"    {{0x{start:06X}, 0x{end:06X}}},"
        )

    lines.append("};")

    lines.append("")
    lines.append(f"table<empty_struct> {name} {{{name}_ranges, {name}_ranges + std::size({name}_ranges)}};")

    return "\n".join(lines)


def generate_cpp(
        xid_start: list[tuple[int, int]],
        xid_continue: list[tuple[int, int]],
) -> str:
    return f"""\
// Autogenerated by {Path(__file__).resolve()}! Do not Edit!

#include <dwhbll/unicode/table.h>

#include <array>
#include <cstdint>

namespace dwhbll::unicode::properties {{

{cpp_ranges("XID_Start", xid_start)}

{cpp_ranges("XID_Continue", xid_continue)}

}}
"""

def main() -> None:
    if len(sys.argv) != 3:
        print("Usage: generate.py <UCD.zip location> <output file>")

    zipf = Path(sys.argv[1]).resolve()
    sfile = Path(sys.argv[2]).resolve()

    with open(zipf, 'rb') as file:
        data = file.read()

    xid_start = merge_ranges(
        parse_property(data, "XID_Start")
    )

    xid_continue = merge_ranges(
        parse_property(data, "XID_Continue")
    )

    print(f"XID_Start:     {len(xid_start):,} ranges")
    print(f"XID_Continue:  {len(xid_continue):,} ranges")

    output = generate_cpp(xid_start, xid_continue)

    with open(sfile, 'w', encoding="utf-8") as file:
        file.write(output)

    print(f"Generated {sfile}")


if __name__ == "__main__":
    main()
