from __future__ import annotations

import io
import sys
import zipfile
from pathlib import Path


def parse_property(data: bytes, file: str, wanted_property: str) -> list[tuple[int, int]]:
    ranges = []

    with zipfile.ZipFile(io.BytesIO(data)) as zf:
        with zf.open(file) as f:
            for raw_line in io.TextIOWrapper(f, encoding="utf-8"):
                line = raw_line.split("#", 1)[0].strip()

                if not line:
                    continue

                codepoints, property_name = map(
                    str.strip,
                    line.split(";", 1),
                )

                if property_name != wanted_property:
                    continue

                if ".." in codepoints:
                    first, last = codepoints.split("..")
                    start = int(first, 16)
                    end = int(last, 16)
                else:
                    start = end = int(codepoints, 16)

                ranges.append((start, end))

    return ranges


def parse_name_aliases(data: bytes) -> list[tuple[str, int]]:
    aliases = []

    with zipfile.ZipFile(io.BytesIO(data)) as zf:
        with zf.open("NameAliases.txt") as f:
            for raw_line in io.TextIOWrapper(f, encoding="utf-8"):
                line = raw_line.split("#", 1)[0].strip()

                if not line:
                    continue

                codepoint, alias, _ = map(
                    str.strip,
                    line.split(";", 2),
                )

                aliases.append((alias, int(codepoint, 16)))

    return aliases


def merge_ranges(ranges: list[tuple[int, int]]) -> list[tuple[int, int]]:
    if not ranges:
        return []

    ranges = sorted(ranges)

    merged = [ranges[0]]

    for start, end in ranges[1:]:
        prev_start, prev_end = merged[-1]

        if start <= prev_end + 1:
            merged[-1] = (prev_start, max(prev_end, end))
        else:
            merged.append((start, end))

    return merged


def cpp_ranges(name: str, ranges: list[tuple[int, int]]) -> str:
    lines = [
        f"static table<empty_struct>::elem {name}_ranges[] = {{",
    ]

    for start, end in ranges:
        lines.append(
            f"    {{0x{start:06X}, 0x{end:06X}}},"
        )

    lines.append("};")

    lines.append("")
    lines.append(f"table<empty_struct> {name} {{{name}_ranges, {name}_ranges + std::size({name}_ranges)}};")

    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 3:
        print("Usage: generate.py <UCD.zip location> <output file>")

    zipf = Path(sys.argv[1]).resolve()
    sfile = Path(sys.argv[2]).resolve()

    with open(zipf, 'rb') as file:
        data = file.read()

    xid_start = merge_ranges(
        parse_property(data, "DerivedCoreProperties.txt", "XID_Start")
    )

    xid_continue = merge_ranges(
        parse_property(data, "DerivedCoreProperties.txt", "XID_Continue")
    )

    id_copmpat_math_start = merge_ranges(
        parse_property(data, "PropList.txt", "ID_Compat_Math_Start")
    )

    id_copmpat_math_continue = merge_ranges(
        parse_property(data, "PropList.txt", "ID_Compat_Math_Continue")
    )

    name_aliases = parse_name_aliases(data)

    print(f"XID_Start:     {len(xid_start):,} ranges")
    print(f"XID_Continue:  {len(xid_continue):,} ranges")
    print(f"ID_Compat_Math_Start:     {len(id_copmpat_math_start):,} ranges")
    print(f"ID_Compat_Math_Continue:  {len(id_copmpat_math_continue):,} ranges")
    print(f"NameAliases.txt: {len(name_aliases):,} aliases")

    output = f"""// Autogenerated by {Path(__file__).resolve()}! Do not Edit!

#include <dwhbll/unicode/table.h>

#include <array>
#include <cstdint>

namespace dwhbll::unicode {{

namespace properties {{

"""

    output += "\n\n".join([cpp_ranges(name, body) for name, body in {"XID_Start": xid_start, "XID_Continue": xid_continue, "ID_Compat_Math_Start": id_copmpat_math_start, "ID_Compat_Math_Continue": id_copmpat_math_continue}.items()])

    output += "\n\n}\n\n namespace aliases {"

    output += f"\n\nstd::unordered_map<std::string, char32_t> name_aliases_to_codepoint {{"

    for name, codepoint in name_aliases:
        output += f"    {{\"{name}\", 0x{codepoint:06X}}},\n"

    output += "};\n"

    output += "\n\n}\n\n}"

    with open(sfile, 'w', encoding="utf-8") as file:
        file.write(output)

    print(f"Generated {sfile}")


if __name__ == "__main__":
    main()
