name: Build and test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer:
          - asan_ubsan
          - tsan
          - ubsan
          - lsan

    container:
      image: debian:forky

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y gcc-16 g++-16 cmake ninja-build liburing-dev pkgconf python3-minimal

      - name: Build
        run: |
          CC=gcc-16 CXX=g++-16 cmake -B build . -G Ninja -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_HARDEN=ON -DBUILD_HARDEN_EXPENSIVE=ON \
            -DDWHBLL_SANITIZER=${{ matrix.sanitizer }} \
            -DDWHBLL_TESTS=ON -DDWHBLL_BENCHMARKS=ON \
            -DDWHBLL_UNICODE_SUPPORT=ON -DDWHBLL_DWCPP_CPP=ON
          cmake --build build

      - name: Test
        env:
          ASAN_OPTIONS: "halt_on_error=1:detect_leaks=1:check_initialization_order=1:strict_init_order=1:detect_stack_use_after_return=1"
          UBSAN_OPTIONS: "halt_on_error=1:print_stacktrace=1"
          TSAN_OPTIONS: "halt_on_error=1:second_deadlock_stack=1"
          LSAN_OPTIONS: "halt_on_error=1"
        run: |
          ./build/dwhbll_test
