name: Build

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:forky

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y gcc-16 g++-16 cmake ninja-build liburing-dev pkgconf python3-minimal

      - name: Build
        run: |
          CC=gcc-16 CXX=g++-16 cmake -B build . -DCMAKE_BUILD_TYPE=Debug -DDWHBLL_TESTS=ON -G Ninja
          cmake --build build

      - name: Test
        run: |
          ctest --test-dir build
